name: simple-pipeline
on: [workflow_dispatch]

jobs:
 run-js-test:
  runs-on: ubuntu-latest
 
  steps:
  - name: Checkout repository
    uses: action/checkout@v3

  - name: Setup Node.js
    uses: actions/setup-node@v3
    with:
     node-version: '18.17.0'
  - name: Install dependencies
    run: npm install jest

  - name: Run test
    run: npm test
