name: main
on: manual
jobs:
job_name:
runs-on: ubuntu-latest
steps:
- name: Checkout repository
users: action/checkout@v3

- name: Setup Node.js
users: actions/setup-node@v3
with:
node-version: 'v18.17.0'
- name: Install dependencies
run: npm install

- name: Run test
run: npm test
